Repository Washington-County/COUNTY-DRUPAL, pull requests merged in 2021-08, with the labels that each got.

#136 WCOR-1138: Install and configure Linkit module.
  composer.json
  composer.lock
  config/default/core.extension.yml
  config/default/editor.editor.basic_html.yml
  config/default/filter.format.basic_html.yml
  config/default/image.style.linkit_result_thumbnail.yml
  config/default/linkit.linkit_profile.default.yml
Labels: Completed Code Review, Completed QA, Enhancement

#137 WCOR-1127: Simple custom theme to start twig development.
  composer.lock
  config/default/block.block.washco_account_menu.yml
  config/default/block.block.washco_breadcrumbs.yml
  config/default/block.block.washco_content.yml
  config/default/block.block.washco_help.yml
  config/default/block.block.washco_main_menu.yml
  config/default/block.block.washco_messages.yml
  config/default/block.block.washco_page_title.yml
  config/default/block.block.washco_powered.yml
  config/default/block.block.washco_primary_admin_actions.yml
  config/default/block.block.washco_primary_local_tasks.yml
  config/default/block.block.washco_secondary_local_tasks.yml
  config/default/block.block.washco_site_branding.yml
  config/default/block.block.washco_syndicate.yml
  config/default/block.block.washco_views_block__alerts_alert_page_block.yml
  config/default/block.block.washco_views_block__building_service_locations_block_1.yml
  config/default/block.block.washco_views_block__group_page_menu_block_group_homepage_menu.yml
  config/default/block.block.washco_views_block__group_page_menu_block_menu_of_child_pages.yml
  config/default/block.block.washco_views_block__group_page_menu_block_menu_of_siblings.yml
  config/default/block.block.washco_views_block__manage_group_block_manage_group.yml
  config/default/block.block.washco_views_block__news_block_recent_group_news.yml
  config/default/block.block.washco_views_block__notifications_block_notifications.yml
  config/default/core.extension.yml
  config/default/system.theme.yml
  docroot/sites/default/development.services.yml
  docroot/sites/default/settings.local.php
  docroot/sites/default/settings.php
  docroot/themes/washco/LICENSE.txt
  docroot/themes/washco/config/install/.gitadd
  docroot/themes/washco/css/bootstrap/bootstrap-grid.css
  docroot/themes/washco/css/bootstrap/bootstrap-grid.min.css
  docroot/themes/washco/css/bootstrap/bootstrap-reboot.css
  docroot/themes/washco/css/bootstrap/bootstrap-reboot.min.css
  docroot/themes/washco/css/bootstrap/bootstrap.css
  docroot/themes/washco/css/bootstrap/bootstrap.min.css
  docroot/themes/washco/css/ckeditor.css
  docroot/themes/washco/css/style.css
  docroot/themes/washco/img/right-arrow.svg
  docroot/themes/washco/js/bootstrap/bootstrap.bundle.js
  docroot/themes/washco/js/bootstrap/bootstrap.bundle.js.map
  docroot/themes/washco/js/bootstrap/bootstrap.bundle.min.js
  docroot/themes/washco/js/bootstrap/bootstrap.bundle.min.js.map
  docroot/themes/washco/js/bootstrap/bootstrap.js
  docroot/themes/washco/js/bootstrap/bootstrap.js.map
  docroot/themes/washco/js/bootstrap/bootstrap.min.js
  docroot/themes/washco/js/bootstrap/bootstrap.min.js.map
  docroot/themes/washco/js/main.js
  docroot/themes/washco/js/tether.min.js
  docroot/themes/washco/screenshot.png
  docroot/themes/washco/templates/footer.html.twig
  docroot/themes/washco/templates/header.html.twig
  docroot/themes/washco/templates/html.html.twig
  docroot/themes/washco/templates/menu/menu--main.html.twig
  docroot/themes/washco/templates/page.html.twig
  docroot/themes/washco/washco.features.yml
  docroot/themes/washco/washco.info.yml
  docroot/themes/washco/washco.libraries.yml
  docroot/themes/washco/washco.theme
Labels: Enhancement, Completed QA, Completed Code Review

#140 hotfix/solr-dev: Disable read-only for all environments. Sync solr da…
  config/default/config_split.config_split.dev.yml
  config/default/search_api.index.acquia_search_index.yml
  config/envs/dev/search_api.index.acquia_search_index.yml
  docroot/sites/default/settings.php
Labels: Bug Fix, Completed QA, Completed Code Review

#138 WCOR-1133: Create Group Manage media view
  config/default/core.entity_form_display.media.document.default.yml
  config/default/core.entity_form_display.media.document.media_library.yml
  config/default/core.entity_form_display.media.image.default.yml
  config/default/core.entity_form_display.media.image.media_library.yml
  config/default/core.entity_form_display.media.video.default.yml
  config/default/core.entity_form_display.media.video.media_library.yml
  config/default/filter.format.basic_html.yml
  config/default/views.view.manage_group_media.yml
Labels: Enhancement, Completed QA, Completed Code Review

#145 hotfix/core-9.2.4: Security update for CKEditor.
  composer.json
  composer.lock
Labels: Bug Fix, Merge Ready

#139 WCOR-1115: Create a standard contact information view-page for groups
  config/default/block.block.views_block__associated_groups_block_1.yml
  config/default/block.block.views_block__associated_groups_block_1_2.yml
  config/default/block.block.washco_views_block__building_service_locations_block_1.yml
  config/default/block.block.washco_views_block__group_page_menu_block_group_homepage_menu.yml
  config/default/block.block.washco_views_block__group_page_menu_block_menu_of_child_pages.yml
  config/default/block.block.washco_views_block__group_page_menu_block_menu_of_siblings.yml
  config/default/block.block.washco_views_block__manage_group_block_manage_group.yml
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.teaser.yml
  config/default/field.field.node.group.field_primary_service_location.yml
  config/default/field.storage.node.field_primary_service_location.yml
  config/default/views.view.associated_groups.yml
  config/default/views.view.groups.yml
  config/default/views.view.service_location_reference.yml
Labels: Enhancement, Completed QA, Completed Code Review

#146 WCOR-1064: Install Views Bulk Operations and Views Bulk Edit
  composer.json
  composer.lock
  config/default/core.extension.yml
  config/default/system.action.media_edit_action.yml
  config/default/system.action.node_edit_action.yml
  config/default/system.action.taxonomy_term_edit_action.yml
  config/default/system.action.user_edit_action.yml
  config/default/views.view.content.yml
  config/default/views.view.manage_group_content.yml
  config/default/views.view.manage_group_media.yml
  config/default/views.view.media.yml
  config/default/views.view.media_library.yml
Labels: Enhancement, Completed QA, Completed Code Review

#147 WCOR-1104: Add translation selection menu block.
  composer.lock
  config/default/block.block.views_block__translation_block_1.yml
  config/default/views.view.translation.yml
Labels: Enhancement, Completed QA, Completed Code Review

#150 WCOR-1166: BLT custom:secret cleanup.
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
  docroot/sites/default/settings.php
Labels: Enhancement, Completed QA, Completed Code Review

#152 WCOR-0: Set seckit directives to prevent log reporting flooding.
  config/default/seckit.settings.yml
  config/envs/ah_other/seckit.settings.yml
Labels: Enhancement, Completed QA, Completed Code Review
