Repository Washington-County/COUNTY-DRUPAL, pull requests merged in 2021-12, with the labels that each got.

#276 WCOR-1219: Bulk PDF upload.
  config/default/core.entity_form_display.media.document.default.yml
  config/default/core.entity_form_display.media.document.media_library.yml
  config/default/core.entity_view_display.media.document.default.yml
  config/default/core.entity_view_display.media.document.embedded.yml
  config/default/core.entity_view_display.media.document.embedded_with_description.yml
  config/default/core.entity_view_display.media.document.media_library.yml
  config/default/feeds.feed_type.pdf_documents.yml
  config/default/field.field.media.document.feeds_item.yml
  config/default/field.field.media.document.field_media_file.yml
  config/default/field.storage.media.feeds_item.yml
  config/default/field.storage.media.field_media_file.yml
Labels: Merge Ready

#300 WCOR-1231: CKEditor Accordion Widget Tool
  config/default/core.extension.yml
  config/default/editor.editor.basic_html.yml
  config/default/filter.format.basic_html.yml
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/ckeditor_accordion.info.yml
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/ckeditor_accordion.module
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/js/plugins/accordion/dialogs/accordion.js
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/js/plugins/accordion/images/icon-hdpi.png
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/js/plugins/accordion/images/icon.png
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/js/plugins/accordion/plugin.js
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/js/plugins/accordion/styles/widget.css
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/src/Plugin/CKEditorPlugin/Accordion.php
  docroot/sites/default/development.services.yml
  docroot/sites/default/settings.php
Labels: enhancement, Completed QA, Completed Code Review

#314 WCOR-0: Bugfix to address schema-json vulnerability and deprecated calc.
  docroot/themes/custom/westy/package-lock.json
  docroot/themes/custom/westy/package.json
  docroot/themes/custom/westy/src/components/form/_form.scss
Labels: bugfix, Completed QA, Completed Code Review

#313 WCOR-1236: Prep environments for PHP 8.0.
  .ddev/config.yaml
  .lando.yml
  acquia-pipelines.yaml
  composer.json
  composer.lock
Labels: enhancement, Completed QA, Completed Code Review

#328 WCOR-0: Enable field type to determine page layout.
  docroot/themes/custom/westy/templates/content/node--page--type--contact-list.html.twig
  docroot/themes/custom/westy/templates/content/node--page.html.twig
Labels: bugfix, Completed QA, Completed Code Review

#335 WCOR-0: Fix broken departments view.
  config/default/core.entity_view_display.node.group.teaser.yml
  docroot/themes/custom/westy/westy.theme
Labels: bugfix, Merge Ready

#337 WCOR-1235: Enable card widgets in CKEditor.
  config/default/core.extension.yml
  config/default/editor.editor.basic_html.yml
  config/default/filter.format.basic_html.yml
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/js/plugins/accordion/dialogs/accordion.js
  docroot/modules/custom/custom_ckeditor/ckeditor_card/ckeditor_card.info.yml
  docroot/modules/custom/custom_ckeditor/ckeditor_card/ckeditor_card.module
  docroot/modules/custom/custom_ckeditor/ckeditor_card/js/plugins/card/dialogs/card.js
  docroot/modules/custom/custom_ckeditor/ckeditor_card/js/plugins/card/images/icon-hdpi.png
  docroot/modules/custom/custom_ckeditor/ckeditor_card/js/plugins/card/images/icon.png
  docroot/modules/custom/custom_ckeditor/ckeditor_card/js/plugins/card/plugin.js
  docroot/modules/custom/custom_ckeditor/ckeditor_card/js/plugins/card/styles/widget.css
  docroot/modules/custom/custom_ckeditor/ckeditor_card/src/Plugin/CKEditorPlugin/Card.php
  docroot/themes/custom/westy/src/scss/components/_cards.scss
  docroot/themes/custom/westy/src/scss/westy.style.scss
Labels: enhancement, Completed QA

#339 WCOR-1237: Setup A and Button tag styling in CKEditor.
  config/default/editor.editor.basic_html.yml
  config/default/filter.format.basic_html.yml
  docroot/themes/custom/westy/src/scss/base/_elements.scss
Labels: enhancement, Needs Code Review, Completed QA
