Repository Washington-County/COUNTY-DRUPAL, pull requests merged in 2021-07, with the labels that each got.

#114 WCOR-1110: Add reCaptcha module.
  composer.json
  composer.lock
  config/default/captcha.settings.yml
  config/default/core.extension.yml
  config/default/recaptcha.settings.yml
Labels: Completed Code Review, Completed QA, Enhancement, Merge Ready

#111 WCOR-1116: Ensure clean legacy redirect for documents.
  composer.json
  composer.lock
  config/default/core.entity_view_display.media.document.default.yml
  config/default/core.extension.yml
  config/default/media.settings.yml
  config/default/pathauto.pattern.media_default.yml
  config/default/rabbit_hole.behavior_settings.media_type_document.yml
  config/default/rabbit_hole.behavior_settings.media_type_image.yml
  config/default/rabbit_hole.behavior_settings.media_type_video.yml
  config/default/user.role.anonymous.yml
  config/default/user.role.authenticated.yml
Labels: Completed Code Review, Completed QA, Enhancement, Merge Ready

#113 WCOR-1049: Install and enable drupal/devel for other and dev.
  composer.json
  composer.lock
  config/default/config_split.config_split.ah_other.yml
  config/default/config_split.config_split.dev.yml
  config/envs/ah_other/devel.settings.yml
  config/envs/ah_other/devel.toolbar.settings.yml
  config/envs/ah_other/system.menu.devel.yml
  config/envs/dev/devel.settings.yml
  config/envs/dev/devel.toolbar.settings.yml
  config/envs/dev/system.menu.devel.yml
  docroot/sites/default/settings.php
Labels: Completed Code Review, Completed QA, Enhancement

#115 WCOR-0: Reinstall packages after being removed prior to a patch install.
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
  composer.json
  composer.lock
Labels: Bug Fix, Completed Code Review, Completed QA

#119 WCOR-0: Update Captcha settings to remove from login forms.
  config/default/captcha.settings.yml
Labels: Bug Fix, Completed Code Review, Completed QA, Merge Ready

#116 WCOR-1050: Identify and add language set for core multilingual.
  config/default/language.entity.ar.yml
  config/default/language.entity.en.yml
  config/default/language.entity.es.yml
  config/default/language.entity.fa.yml
  config/default/language.entity.fil.yml
  config/default/language.entity.ja.yml
  config/default/language.entity.km.yml
  config/default/language.entity.ko.yml
  config/default/language.entity.ru.yml
  config/default/language.entity.so.yml
  config/default/language.entity.und.yml
  config/default/language.entity.vi.yml
  config/default/language.entity.zh-hans.yml
  config/default/language.entity.zh-hant.yml
  config/default/language.entity.zxx.yml
  config/default/language.negotiation.yml
  config/default/pathauto.pattern.news.yml
  config/default/pathauto.pattern.pages.yml
  config/default/pathauto.settings.yml
  config/default/search_api_solr.solr_field_type.text_ar_6_0_0.yml
  config/default/search_api_solr.solr_field_type.text_ar_7_0_0.yml
  config/default/search_api_solr.solr_field_type.text_fa_7_0_0.yml
  config/default/search_api_solr.solr_field_type.text_ja_6_0_0.yml
  config/default/search_api_solr.solr_field_type.text_ja_8_0_0.yml
  config/default/search_api_solr.solr_field_type.text_phonetic_ru_7_0_0.yml
  config/default/search_api_solr.solr_field_type.text_ru_6_0_0.yml
  config/default/search_api_solr.solr_field_type.text_ru_7_0_0.yml
  config/default/search_api_solr.solr_field_type.text_zh-hans_7_0_0.yml
  config/default/search_api_solr.solr_field_type.text_zh-hant_7_0_0.yml
  config/default/views.view.content.yml
Labels: Completed Code Review, Completed QA, Enhancement

#118 WCOR-1119: Create group reference view and apply to content types.
  config/default/field.field.node.contact.field_group.yml
  config/default/field.field.node.group.field_parent.yml
  config/default/field.field.node.news.field_group.yml
  config/default/field.field.node.notification.field_group.yml
  config/default/field.field.node.page.field_group.yml
  config/default/views.view.group_reference.yml
Labels: Completed Code Review, Completed QA, Enhancement

#120 WCOR-1122: Install and enable field_group.
  composer.json
  composer.lock
  config/default/core.extension.yml
Labels: Completed Code Review, Completed QA, Enhancement

#123 WCOR-0: Correct config mismatch.
  config/default/core.entity_view_display.node.building.default.yml
  config/default/core.entity_view_display.node.building.teaser.yml
Labels: Bug Fix, Completed Code Review

#125 WCOR-1082: Add social media fields to Group content type.
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.teaser.yml
  config/default/field.field.node.group.field_facebook.yml
  config/default/field.field.node.group.field_linkedin.yml
  config/default/field.field.node.group.field_twitter.yml
  config/default/field.field.node.group.field_youtube.yml
  config/default/field.storage.node.field_facebook.yml
  config/default/field.storage.node.field_linkedin.yml
  config/default/field.storage.node.field_twitter.yml
  config/default/field.storage.node.field_youtube.yml
Labels: Completed Code Review, Completed QA, Enhancement

#129 WCOR-0: Update core to 9.2.2.
  composer.json
  composer.lock
Labels: Bug Fix, Completed QA

#124 WCOR-1062: Group News View
  config/default/block.block.views_block__news_block_recent_group_news.yml
  config/default/core.entity_view_display.node.news.teaser.yml
  config/default/views.view.manage_group_content.yml
  config/default/views.view.news.yml
Labels: Completed Code Review, Completed QA, Enhancement

#131 WCOR-1075: Implement SAML based login.
  composer.json
  composer.lock
  config/default/core.entity_form_display.user.user.default.yml
  config/default/core.extension.yml
  config/default/simplesamlphp_auth.settings.yml
  docroot/simplesaml
  simplesamlphp_files/config/authsources.php
  simplesamlphp_files/config/config.php
  simplesamlphp_files/metadata/saml20-idp-remote.php
  simplesamlphp_files/metadata/saml20-sp-remote.php
  simplesamlphp_files/www.htaccess
Labels: Completed Code Review, Completed QA, Enhancement, Merge Ready

#132 redirect http to https.
  docroot/sites/default/settings.php
Labels: Completed Code Review, Completed QA, Enhancement

#133 hotfix/simplesamlphp: Disable simplesamlphp_auth for ide/ode
  config/default/config_split.config_split.ah_other.yml
  config/envs/ah_other/simplesamlphp_auth.settings.yml
Labels: Bug Fix

#130 WCOR-1113: Install Security Kit module and create initial configuration.
  composer.json
  composer.lock
  config/default/config_split.config_split.ah_other.yml
  config/default/core.extension.yml
  config/default/seckit.settings.yml
  config/envs/ah_other/seckit.settings.yml
Labels: Completed Code Review, Completed QA, Enhancement

#134 WCOR-1137: Import contact information (primary tel and web email) for departments and divisions
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.teaser.yml
  config/default/feeds.feed_type.central_system_groups.yml
  config/default/field.field.node.group.feeds_item.yml
  config/default/field.field.node.group.field_summary.yml
  config/default/field.storage.node.field_summary.yml
Labels: Enhancement, Merge Ready
