Repository Washington-County/COUNTY-DRUPAL, pull requests merged in 2021-11, with the labels that each got.

#238 WCOR-1206: Implement CKeditor changes & page element styles.
  config/default/editor.editor.basic_html.yml
  config/default/filter.format.basic_html.yml
  docroot/themes/custom/westy/src/scss/base/_elements.scss
Labels: enhancement, Completed QA, Completed Code Review

#239 WCOR-1216: Menu toolbar for admin views.
  config/default/system.menu.admin-views.yml
  config/default/toolbar_menu.toolbar_menu_element.admin_views.yml
Labels: enhancement, Completed QA, Completed Code Review

#249 WCOR-0: Use npm ci instead of npm install.
  blt/blt.yml
Labels: bugfix, Completed QA, Completed Code Review

#241 WCOR-1210: implement client site hiearchical select and big menu to modify menu approach
  composer.json
  composer.lock
  config/default/bigmenu.settings.yml
  config/default/block.block.sitemap.yml
  config/default/block.block.westy_breadcrumbs.yml
  config/default/block.block.westy_page_title.yml
  config/default/block.block.westy_primary_admin_actions.yml
  config/default/block.block.westy_primary_local_tasks.yml
  config/default/block.block.westy_secondary_local_tasks.yml
  config/default/block.block.westy_views_block__group_page_menu_block_group_homepage_menu.yml
  config/default/block.block.westy_views_block__group_page_menu_block_menu_of_child_pages.yml
  config/default/block.block.westy_views_block__group_page_menu_block_menu_of_siblings.yml
  config/default/block.block.westy_views_block__groups_block_divisions.yml
  config/default/block.block.westy_views_block__groups_block_programs.yml
  config/default/block.block.westy_views_block__manage_group_block_manage_group.yml
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_view_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.teaser.yml
  config/default/core.entity_view_display.node.page.default.yml
  config/default/core.entity_view_display.node.page.teaser.yml
  config/default/core.extension.yml
  config/default/field.field.node.page.field_menu_parent.yml
  config/default/field.field.node.page.field_show_in_menu.yml
  config/default/field.field.node.page.field_sort_weight.yml
  config/default/menu_breadcrumb.settings.yml
  config/default/node.type.group.yml
  config/default/node.type.page.yml
  config/default/node.type.resource.yml
  config/default/node.type.service_location.yml
  config/default/pathauto.pattern.pages.yml
  config/default/system.menu.site-map.yml
  config/default/views.view.content.yml
  config/default/views.view.manage_group.yml
  docroot/themes/custom/westy/package-lock.json
  docroot/themes/custom/westy/src/scss/content/_node.article.scss
  docroot/themes/custom/westy/templates/menu/menu--site-map.html.twig
Labels: enhancement, Completed QA, Completed Code Review

#246 WCOR-0: Adjust blockquote and list styles.
  docroot/themes/custom/westy/src/scss/base/_elements.scss
Labels: bugfix, Completed QA, Completed Code Review

#247 WCOR-0: Enhance Content Migration Status admin view.
  config/default/views.view.content_migration_status.yml
Labels: bugfix, Completed QA, Completed Code Review

#251 WCOR-1218: Streamline contacts and allow for grouping and separate views.
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_view_display.node.contact.default.yml
  config/default/core.entity_view_display.node.page.default.yml
  config/default/core.entity_view_display.node.page.teaser.yml
  config/default/field.field.node.page.field_contact.yml
  config/default/field.storage.node.field_contact.yml
  config/default/node.type.contact.yml
  config/default/views.view.contacts_reference.yml
  docroot/themes/custom/westy/.gitignore
  docroot/themes/custom/westy/config/proxy.js
  docroot/themes/custom/westy/src/scss/base/_elements.scss
  docroot/themes/custom/westy/templates/content/node--page--type--contact-list.html.twig
  docroot/themes/custom/westy/templates/content/node--page.html.twig
  docroot/themes/custom/westy/webpack.mix.js
Labels: enhancement, Completed QA, Completed Code Review

#254 WCOR-1214: Setup CKEditor bootstrap grid widget.
  config/default/core.extension.yml
  config/default/editor.editor.basic_html.yml
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/LICENSE.txt
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/README.md
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/ckeditor_bootstrap_grid.info.yml
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgetbootstrap/contents.css
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgetbootstrap/icons/widgetbootstrapLeftCol.png
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgetbootstrap/icons/widgetbootstrapRightCol.png
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgetbootstrap/icons/widgetbootstrapThreeCol.png
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgetbootstrap/icons/widgetbootstrapTwoCol.png
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgetbootstrap/plugin.es6.js
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgetbootstrap/plugin.js
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgettemplatemenu/icons/widgettemplatemenu.png
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgettemplatemenu/plugin.es6.js
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/js/plugins/widgettemplatemenu/plugin.js
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/src/Plugin/CKEditorPlugin/WidgetBootstrap.php
  docroot/modules/custom/custom_ckeditor/ckeditor_bootstrap_grid/src/Plugin/CKEditorPlugin/WidgetTemplateMenu.php
Labels: enhancement, Completed QA, Completed Code Review

#258 bugfix/WCOR-0: Disable EVA phone formatting.
  blt/blt.yml
  config/default/core.entity_view_display.node.contact.default.yml
  config/default/core.entity_view_display.node.group.default.yml
  config/default/core.entity_view_display.node.page.default.yml
  config/default/rabbit_hole.behavior_settings.node_type_contact.yml
  config/default/views.view.phone_number_formatter.yml
  docroot/modules/custom/wcor/src/PhoneExtension.php
  docroot/modules/custom/wcor/wcor.services.yml
  docroot/themes/custom/westy/templates/content/node--page--type--contact-list.html.twig
  docroot/themes/custom/westy/templates/field/field--field-phone-extension.html.twig
  docroot/themes/custom/westy/templates/field/field--field-phone.html.twig
  docroot/themes/custom/westy/westy.theme
Labels: bugfix, Completed QA, Completed Code Review

#259 WCOR-0: Page presentation and pathauto bugfixes.
  config/default/core.entity_view_display.node.page.default.yml
  config/default/pathauto.settings.yml
  config/default/views.view.content_migration_status.yml
  docroot/themes/custom/westy/src/scss/layout/_page.content.scss
Labels: bugfix, Completed QA, Completed Code Review

#264 WCOR-0: Update core and modules.
  composer.json
  composer.lock
  config/default/admin_toolbar.settings.yml
  config/default/s3fs.settings.yml
  config/default/system.action.webform_archive_action.yml
  config/default/system.action.webform_close_action.yml
  config/default/system.action.webform_delete_action.yml
  config/default/system.action.webform_open_action.yml
  config/default/system.action.webform_unarchive_action.yml
  config/default/webform.settings.yml
  config/default/webform.webform.contact.yml
  config/default/webform.webform.example_accessibility_advanced.yml
  config/default/webform.webform.example_accessibility_basic.yml
  config/default/webform.webform.example_accessibility_containers.yml
  config/default/webform.webform.example_accessibility_labels.yml
  config/default/webform.webform.example_accessibility_wizard.yml
  config/default/webform.webform.webform_example_element.yml
Labels: bugfix, Merge Ready, Updates

#268 WCOR-0: Security update for core.
  composer.json
  composer.lock
Labels: bugfix, Merge Ready

#269 WCOR-1217: Convert social media EVAs to Twig rendering.
  composer.lock
  config/default/core.entity_view_display.node.group.default.yml
  docroot/themes/custom/westy/templates/field/field--field-facebook.html.twig
  docroot/themes/custom/westy/templates/field/field--field-twitter.html.twig
  docroot/themes/custom/westy/templates/field/field--field-youtube.html.twig
Labels: enhancement, Completed QA, Completed Code Review

#270 WCOR-0: Clean up following social media fields Twig story.
  config/default/core.entity_view_display.node.group.default.yml
  config/default/field.field.node.group.field_youtube.yml
Labels: bugfix, Completed QA, Completed Code Review

#273 WCOR-0: Update core to 9.2.10.
  composer.json
  composer.lock
Labels: Needs QA, hotfix

#271 WCOR-1222: Group documents list / search view.
  config/default/block.block.contenttype.yml
  config/default/block.block.documents_fy.yml
  config/default/block.block.documents_tags.yml
  config/default/block.block.group.yml
  config/default/block.block.group_2.yml
  config/default/block.block.month.yml
  config/default/block.block.westy_views_block__building_service_locations_block_1.yml
  config/default/block.block.westy_views_block__translation_block_1.yml
  config/default/block.block.year.yml
  config/default/core.entity_form_display.media.document.default.yml
  config/default/core.entity_form_display.media.document.media_library.yml
  config/default/core.entity_form_display.taxonomy_term.tags.default.yml
  config/default/core.entity_view_display.media.document.default.yml
  config/default/core.entity_view_display.media.document.embedded.yml
  config/default/core.entity_view_display.media.document.embedded_with_description.yml
  config/default/core.entity_view_display.media.document.media_library.yml
  config/default/core.entity_view_display.taxonomy_term.tags.default.yml
  config/default/facets.facet.documents_fy.yml
  config/default/facets.facet.documents_tags.yml
  config/default/facets.facet_source.search_api__views_page__documents_solr__page_documents.yml
  config/default/field.field.media.document.field_fiscal_year.yml
  config/default/field.field.media.document.field_tags.yml
  config/default/field.field.taxonomy_term.tags.field_group.yml
  config/default/field.storage.media.field_fiscal_year.yml
  config/default/field.storage.media.field_tags.yml
  config/default/field.storage.taxonomy_term.field_group.yml
  config/default/language.content_settings.taxonomy_term.tags.yml
  config/default/pathauto.pattern.taxonomy_term_default.yml
  config/default/search_api.index.acquia_search_index.yml
  config/default/taxonomy.vocabulary.tags.yml
  config/default/user.role.content_admin.yml
  config/default/views.view.documents_solr.yml
  docroot/sites/default/development.services.yml
  docroot/themes/custom/westy/src/scss/base/_elements.scss
  docroot/themes/custom/westy/src/scss/layout/_page.content.scss
  docroot/themes/custom/westy/src/scss/media/_embedded.scss
  docroot/themes/custom/westy/src/scss/view/_view.scss
  docroot/themes/custom/westy/templates/media/media--document.html.twig
Labels: enhancement, Completed QA, Completed Code Review
