Repository Washington-County/COUNTY-DRUPAL, pull requests merged in 2021-06, with the labels that each got.

#71 WCOR-0020526: Install and enable views data export module.
  composer.json
  composer.lock
  config/default/core.extension.yml
Labels: Completed Code Review, Completed QA, Enhancement

#74 WCOR-0020523: Install and enable redirect module.
  composer.json
  composer.lock
  config/default/core.entity_form_display.node.alert.default.yml
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_form_display.node.news.default.yml
  config/default/core.entity_form_display.node.notification.default.yml
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_form_display.node.resource.default.yml
  config/default/core.extension.yml
  config/default/language.content_settings.redirect.redirect.yml
  config/default/redirect.settings.yml
  config/default/system.action.redirect_delete_action.yml
  config/default/views.view.redirect.yml
Labels: Completed Code Review, Completed QA, Enhancement

#75 WCOR-0020530: Add contact content type.
  config/default/core.base_field_override.node.contact.promote.yml
  config/default/core.base_field_override.node.contact.status.yml
  config/default/core.base_field_override.node.contact.title.yml
  config/default/core.entity_form_display.node.contact.default.yml
  config/default/core.entity_view_display.node.contact.default.yml
  config/default/field.field.node.contact.field_contact_title.yml
  config/default/field.field.node.contact.field_email.yml
  config/default/field.field.node.contact.field_group.yml
  config/default/field.field.node.contact.field_phone.yml
  config/default/field.field.node.contact.field_phone_help_text.yml
  config/default/field.storage.node.field_contact_title.yml
  config/default/field.storage.node.field_email.yml
  config/default/field.storage.node.field_phone.yml
  config/default/field.storage.node.field_phone_help_text.yml
  config/default/language.content_settings.node.contact.yml
  config/default/node.type.contact.yml
  config/default/rabbit_hole.behavior_settings.node_type_contact.yml
Labels: Completed Code Review, Completed QA, Enhancement

#78 WCOR-0: Fix error when new content type is created.
  config/default/field.storage.node.body.yml
Labels: Bug Fix, Completed Code Review, Completed QA

#76 WCOR-0020512: Add video/audio media type.
  config/default/core.entity_form_display.media.video.default.yml
  config/default/core.entity_form_display.media.video.media_library.yml
  config/default/core.entity_view_display.media.video.default.yml
  config/default/core.entity_view_display.media.video.media_library.yml
  config/default/field.field.media.video.field_caption.yml
  config/default/field.field.media.video.field_creator.yml
  config/default/field.field.media.video.field_group.yml
  config/default/field.field.media.video.field_media_in_library.yml
  config/default/field.field.media.video.field_media_oembed_video.yml
  config/default/field.field.media.video.field_source.yml
  config/default/field.field.media.video.field_transcript.yml
  config/default/field.storage.media.field_creator.yml
  config/default/field.storage.media.field_group.yml
  config/default/field.storage.media.field_media_oembed_video.yml
  config/default/field.storage.media.field_source.yml
  config/default/field.storage.media.field_transcript.yml
  config/default/language.content_settings.media.video.yml
  config/default/media.type.video.yml
Labels: Completed Code Review, Completed QA, Enhancement

#79 WCOR-0020518: Add document media type.
  config/default/core.entity_form_display.media.document.default.yml
  config/default/core.entity_form_display.media.document.media_library.yml
  config/default/core.entity_view_display.media.document.default.yml
  config/default/core.entity_view_display.media.document.media_library.yml
  config/default/editor.editor.basic_html.yml
  config/default/field.field.media.document.field_document_type.yml
  config/default/field.field.media.document.field_group.yml
  config/default/field.field.media.document.field_media_file.yml
  config/default/field.field.media.document.field_media_in_library.yml
  config/default/field.storage.media.field_document_type.yml
  config/default/field.storage.media.field_media_file.yml
  config/default/filter.format.basic_html.yml
  config/default/language.content_settings.media.document.yml
  config/default/media.type.document.yml
Labels: Completed Code Review, Completed QA, Enhancement

#80 WCOR-0020675: Cleanup language selection fields and add in Spanish.
  config/default/core.extension.yml
  config/default/language.content_settings.media.document.yml
  config/default/language.content_settings.media.image.yml
  config/default/language.content_settings.media.video.yml
  config/default/language.content_settings.node.alert.yml
  config/default/language.content_settings.node.contact.yml
  config/default/language.content_settings.node.group.yml
  config/default/language.content_settings.node.notification.yml
  config/default/language.content_settings.node.page.yml
  config/default/language.content_settings.node.resource.yml
  config/default/language.content_settings.path_alias.path_alias.yml
  config/default/language.content_settings.redirect.redirect.yml
  config/default/language.entity.es.yml
  config/default/language.negotiation.yml
  config/default/locale.settings.yml
Labels: Bug Fix, Completed Code Review, Completed QA, Enhancement

#83 WCOR-0: Update core to 9.1.10, admin_toolbar to 3.0.1.
  composer.json
  composer.lock
  config/default/admin_toolbar_tools.settings.yml
Labels: Completed Code Review, Completed QA, Updates

#87 WCOR-0: Changes to custom:catchup
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
Labels: Bug Fix, Completed Code Review, Completed QA

#89 WCOR-0: Fix workflow issue.
  composer.lock
  config/default/core.entity_form_display.node.resource.default.yml
  config/default/workflows.workflow.editorial.yml
Labels: Bug Fix, Needs QA

#91 WCOR-0: Add custom:check blt command.
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
Labels: Completed QA, Enhancement

#92 WCOR-0: Update README.md; story ID convention update, BLT check function info
  README.md
Labels: Completed Code Review, Documentation

#88 WCOR-1080: Add Webform module.
  composer.json
  composer.lock
  config/default/core.base_field_override.node.webform.promote.yml
  config/default/core.entity_form_display.node.webform.default.yml
  config/default/core.entity_view_display.node.webform.default.yml
  config/default/core.entity_view_display.node.webform.teaser.yml
  config/default/core.extension.yml
  config/default/field.field.node.webform.body.yml
  config/default/field.field.node.webform.webform.yml
  config/default/field.storage.node.webform.yml
  config/default/node.type.webform.yml
  config/default/system.action.webform_submission_delete_action.yml
  config/default/system.action.webform_submission_make_lock_action.yml
  config/default/system.action.webform_submission_make_sticky_action.yml
  config/default/system.action.webform_submission_make_unlock_action.yml
  config/default/system.action.webform_submission_make_unsticky_action.yml
  config/default/system.mail.yml
  config/default/views.view.webform_submissions.yml
  config/default/webform.settings.yml
  config/default/webform.webform.contact.yml
  config/default/webform.webform.example_accessibility_advanced.yml
  config/default/webform.webform.example_accessibility_basic.yml
  config/default/webform.webform.example_accessibility_containers.yml
  config/default/webform.webform.example_accessibility_labels.yml
  config/default/webform.webform.example_accessibility_wizard.yml
  config/default/webform.webform.webform_example_element.yml
  config/default/webform.webform_options.country_codes.yml
  config/default/webform.webform_options.country_names.yml
  config/default/webform.webform_options.days.yml
  config/default/webform.webform_options.education.yml
  config/default/webform.webform_options.employment_status.yml
  config/default/webform.webform_options.ethnicity.yml
  config/default/webform.webform_options.gender.yml
  config/default/webform.webform_options.industry.yml
  config/default/webform.webform_options.languages.yml
  config/default/webform.webform_options.likert_agreement.yml
  config/default/webform.webform_options.likert_comparison.yml
  config/default/webform.webform_options.likert_importance.yml
  config/default/webform.webform_options.likert_quality.yml
  config/default/webform.webform_options.likert_satisfaction.yml
  config/default/webform.webform_options.likert_ten_scale.yml
  config/default/webform.webform_options.likert_would_you.yml
  config/default/webform.webform_options.marital_status.yml
  config/default/webform.webform_options.months.yml
  config/default/webform.webform_options.phone_types.yml
  config/default/webform.webform_options.province_codes.yml
  config/default/webform.webform_options.province_names.yml
  config/default/webform.webform_options.relationship.yml
  config/default/webform.webform_options.sex.yml
  config/default/webform.webform_options.sex_icao.yml
  config/default/webform.webform_options.size.yml
  config/default/webform.webform_options.state_codes.yml
  config/default/webform.webform_options.state_names.yml
  config/default/webform.webform_options.state_province_codes.yml
  config/default/webform.webform_options.state_province_names.yml
  config/default/webform.webform_options.time_zones.yml
  config/default/webform.webform_options.titles.yml
  config/default/webform.webform_options.translations.yml
  config/default/webform.webform_options.yes_no.yml
Labels: Completed Code Review, Completed QA

#93 WCOR-0: Update core to 9.2.0
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
  composer.json
  composer.lock
  docroot/.gitignore
  docroot/sites/default/default.services.yml
  docroot/sites/default/default.settings.php
Labels: Completed QA, Enhancement

#98 WCOR-1035: Configure summary field with maxlength.
  composer.json
  composer.lock
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_form_display.node.news.default.yml
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_form_display.node.resource.default.yml
  config/default/core.extension.yml
  config/default/field.field.node.group.field_summary.yml
  config/default/field.field.node.resource.field_summary.yml
  config/default/webform.settings.yml
  config/default/webform.webform.contact.yml
  config/default/webform.webform.example_accessibility_advanced.yml
  config/default/webform.webform.example_accessibility_basic.yml
  config/default/webform.webform.example_accessibility_containers.yml
  config/default/webform.webform.example_accessibility_labels.yml
  config/default/webform.webform.example_accessibility_wizard.yml
  config/default/webform.webform.webform_example_element.yml
  config/default/webform.webform_options.days.yml
  config/default/webform.webform_options.education.yml
  config/default/webform.webform_options.employment_status.yml
  config/default/webform.webform_options.ethnicity.yml
  config/default/webform.webform_options.gender.yml
  config/default/webform.webform_options.industry.yml
  config/default/webform.webform_options.likert_agreement.yml
  config/default/webform.webform_options.likert_comparison.yml
  config/default/webform.webform_options.likert_importance.yml
  config/default/webform.webform_options.likert_quality.yml
  config/default/webform.webform_options.likert_satisfaction.yml
  config/default/webform.webform_options.likert_ten_scale.yml
  config/default/webform.webform_options.likert_would_you.yml
  config/default/webform.webform_options.marital_status.yml
  config/default/webform.webform_options.months.yml
  config/default/webform.webform_options.phone_types.yml
  config/default/webform.webform_options.province_codes.yml
  config/default/webform.webform_options.province_names.yml
  config/default/webform.webform_options.relationship.yml
  config/default/webform.webform_options.sex.yml
  config/default/webform.webform_options.sex_icao.yml
  config/default/webform.webform_options.size.yml
  config/default/webform.webform_options.state_codes.yml
  config/default/webform.webform_options.state_names.yml
  config/default/webform.webform_options.state_province_codes.yml
  config/default/webform.webform_options.state_province_names.yml
  config/default/webform.webform_options.titles.yml
  config/default/webform.webform_options.yes_no.yml
Labels: Completed Code Review, Completed QA, Enhancement, Merge Ready

#96 WCOR-1085: Add a folder in Drupal's docroot to house static microsites and applications
  docroot/apps/.htaccess
Labels: Completed Code Review, Completed QA, Enhancement, Merge Ready

#95 WCOR-0: Hotfix/webform libraries
  acquia-pipelines.yaml
  composer.json
  composer.lock
  config/default/captcha.captcha_point.contact_message_feedback_form.yml
  config/default/captcha.captcha_point.contact_message_personal_form.yml
  config/default/captcha.captcha_point.node_alert_form.yml
  config/default/captcha.captcha_point.node_contact_form.yml
  config/default/captcha.captcha_point.node_group_form.yml
  config/default/captcha.captcha_point.node_news_form.yml
  config/default/captcha.captcha_point.node_notification_form.yml
  config/default/captcha.captcha_point.node_page_form.yml
  config/default/captcha.captcha_point.node_resource_form.yml
  config/default/captcha.captcha_point.node_webform_form.yml
  config/default/captcha.captcha_point.user_login_form.yml
  config/default/captcha.captcha_point.user_pass.yml
  config/default/captcha.captcha_point.user_register_form.yml
  config/default/captcha.settings.yml
  config/default/core.extension.yml
  config/default/honeypot.settings.yml
  config/default/system.advisories.yml
  config/default/system.rss.yml
  config/default/views.settings.yml
Labels: Completed Code Review, Completed QA, Enhancement

#99 WCOR: hotfix/update-blt
  composer.json
  composer.lock
Labels: Completed Code Review, Enhancement

#104 WCOR-1109: Add BLT commands for quicker ODE login and entity view display config exports.
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
Labels: Completed Code Review, Completed QA, Enhancement

#102 WCOR-1089: Implement legacy paths and redirects.
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
  config/default/core.entity_form_display.media.document.default.yml
  config/default/core.entity_form_display.media.document.media_library.yml
  config/default/core.entity_form_display.media.image.default.yml
  config/default/core.entity_form_display.media.image.media_library.yml
  config/default/core.entity_form_display.media.video.default.yml
  config/default/core.entity_form_display.media.video.media_library.yml
  config/default/core.entity_form_display.node.alert.default.yml
  config/default/core.entity_form_display.node.building.default.yml
  config/default/core.entity_form_display.node.contact.default.yml
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_form_display.node.news.default.yml
  config/default/core.entity_form_display.node.notification.default.yml
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_form_display.node.resource.default.yml
  config/default/core.entity_form_display.node.service_location.default.yml
  config/default/core.entity_form_display.node.webform.default.yml
  config/default/core.extension.yml
  docroot/modules/custom/wcor/modules/wcor_legacy_redirects/src/Field/RedirectList.php
  docroot/modules/custom/wcor/modules/wcor_legacy_redirects/src/Plugin/Validation/Constraint/RelativePathConstraint.php
  docroot/modules/custom/wcor/modules/wcor_legacy_redirects/src/Plugin/Validation/Constraint/RelativePathConstraintValidator.php
  docroot/modules/custom/wcor/modules/wcor_legacy_redirects/wcor_legacy_redirects.info.yml
  docroot/modules/custom/wcor/modules/wcor_legacy_redirects/wcor_legacy_redirects.module
  docroot/modules/custom/wcor/templates/block--wcor-legacy-paths-block.html.twig
  docroot/modules/custom/wcor/wcor.info.yml
  docroot/modules/custom/wcor/wcor.module
  docroot/modules/custom/wcor/wcor.views.inc
Labels: Completed Code Review, Completed QA, Enhancement

#105 WCOR-0: Solr update and configuration.
  composer.lock
  config/default/config_split.config_split.other.yml
  config/envs/ah_other/search_api.index.acquia_search_index.yml
Labels: Completed Code Review, Completed QA, Enhancement

#106 WCOR-0: Clean up BLT custom commands.
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
Labels: Completed Code Review, Completed QA, Enhancement

#109 WCOR-0: Config split cleanup and fix.
  config/default/config_split.config_split.ah_other.yml
  config/default/config_split.config_split.dev.yml
  config/default/config_split.config_split.prod.yml
  config/default/config_split.config_split.stage.yml
  config/default/search_api.index.acquia_search_index.yml
  config/default/system.performance.yml
  config/envs/dev/search_api.index.acquia_search_index.yml
  config/envs/prod/system.performance.yml
Labels: Bug Fix, Completed Code Review, Starting QA

#110 WCOR-1118: Configure SMTP to allow for outbound emails.
  config/default/core.extension.yml
  config/default/language.negotiation.yml
  config/default/smtp.settings.yml
  config/default/system.mail.yml
  config/default/system.site.yml
Labels: Completed Code Review, Completed QA, Enhancement
