Repository Washington-County/COUNTY-DRUPAL, pull requests merged in 2021-05, with the labels that each got.

#34 WCOR-0019994: Shield module enablement.
  .gitignore
  config/default/config_split.config_split.dev.yml
  config/default/shield.settings.yml
  docroot/sites/default/settings.php
Labels: enhancement

#35 WCOR-0019791: Add all vocabularies.
  config/default/language.content_settings.taxonomy_term.document_type.yml
  config/default/language.content_settings.taxonomy_term.page_type.yml
  config/default/language.content_settings.taxonomy_term.project_status.yml
  config/default/language.content_settings.taxonomy_term.project_type.yml
  config/default/language.negotiation.yml
  config/default/taxonomy.vocabulary.document_type.yml
  config/default/taxonomy.vocabulary.page_type.yml
  config/default/taxonomy.vocabulary.project_status.yml
  config/default/taxonomy.vocabulary.project_type.yml
Labels: enhancement

#48 WCOR-0019995: Create editorial and media workflows.
  composer.json
  composer.lock
  config/default/core.entity_form_display.node.alert.default.yml
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_form_display.node.news.default.yml
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_form_display.node.resource.default.yml
  config/default/core.extension.yml
  config/default/views.view.moderated_content.yml
  config/default/workflows.workflow.editorial.yml
  config/default/workflows.workflow.media.yml
Labels: Enhancement, Merge Ready

#52 WCOR-0019898: Create initial notification content type and block display
  config/default/block.block.olivero_content.yml
  config/default/block.block.olivero_site_branding.yml
  config/default/block.block.views_block__notifications_block_notifications.yml
  config/default/core.base_field_override.node.notification.promote.yml
  config/default/core.base_field_override.node.notification.status.yml
  config/default/core.entity_form_display.node.notification.default.yml
  config/default/core.entity_view_display.node.notification.default.yml
  config/default/field.field.node.notification.field_group.yml
  config/default/field.field.node.notification.field_notification_body.yml
  config/default/field.storage.node.field_notification_body.yml
  config/default/language.content_settings.node.notification.yml
  config/default/node.type.notification.yml
  config/default/pathauto.pattern.news.yml
  config/default/pathauto.pattern.page.yml
  config/default/rabbit_hole.behavior_settings.node_type_notification.yml
  config/default/views.view.notifications.yml
Labels: Enhancement, Merge Ready

#51 WCOR-0020148: Update README with QA instructions.
  README.md
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
Labels: Completed QA, Documentation, Merge Ready

#55 WCOR-0020190: Change format of News view displays to use teaser format
  config/default/core.entity_view_display.node.news.default.yml
  config/default/core.entity_view_display.node.news.teaser.yml
  config/default/views.view.news.yml
Labels: Completed Code Review, Completed QA, Enhancement, Merge Ready

#54 WCOR-0020263: Add updated date formats.
  config/default/core.date_format.long.yml
  config/default/core.date_format.medium.yml
  config/default/core.date_format.olivero_medium.yml
  config/default/core.date_format.short.yml
Labels: Completed Code Review, Completed QA, Enhancement, Merge Ready

#56 WCOR-0: Update .gitignore to exclude .acquia-cli.yml.
  .gitignore
Labels: Bug Fix, Completed Code Review, Merge Ready

#57 WCOR-0020262: Define the default rich text format
  config/default/editor.editor.basic_html.yml
  config/default/filter.format.basic_html.yml
  config/default/user.role.authenticated.yml
Labels: Completed Code Review, Completed QA, Enhancement, Merge Ready

#59 WCOR-0: Add QA process diagram to README.
  README.md
Labels: Bug Fix, Completed Code Review, Merge Ready

#63 WCOR-0: Core update to 9.1.9.
  composer.json
  composer.lock
Labels: Bug Fix, Merge Ready

#61 WCOR-0020415: Install and enable S3Fs module.
  blt/src/Blt/Plugin/Commands/WashcoCommands.php
  composer.json
  composer.lock
  config/default/core.extension.yml
  config/default/editor.editor.basic_html.yml
  config/default/field.storage.media.field_media_image.yml
  config/default/s3fs.settings.yml
  config/default/system.logging.yml
  config/default/workflows.workflow.media.yml
  docroot/sites/default/settings.php
Labels: Bug Fix, Completed Code Review, Completed QA, Enhancement

#62 WCOR-0019790: Add initial groups view.
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.teaser.yml
  config/default/field.field.node.group.field_summary.yml
  config/default/node.type.group.yml
  config/default/views.view.groups.yml
Labels: Completed Code Review, Completed QA, Enhancement

#64 WCOR-0020478: Migrate departments into group content type.
  composer.json
  composer.lock
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.extension.yml
  config/default/pathauto.pattern.group.yml
Labels: Completed Code Review, Completed QA, Enhancement
