Repository Washington-County/COUNTY-DRUPAL, pull requests merged in 2021-09, with the labels that each got.

#162 WCOR-1073: Enable and configure Google Tag Manager.
  composer.json
  composer.lock
  config/default/core.extension.yml
  config/default/google_tag.container.www.washingtoncountyor.gov.yml
  config/default/google_tag.settings.yml
  config/envs/prod/google_tag.container.www.washingtoncountyor.gov.yml
  config/envs/prod/google_tag.settings.yml
Labels: Merge Ready, Enhancement, Completed QA, Completed Code Review

#165 WCOR-1173: Simplify group reference search.
  config/default/field.field.node.faq.field_group.yml
  config/default/views.view.group_reference.yml
Labels: Enhancement, Completed QA, Completed Code Review

#168 WCOR-0: Remove CSV Importer module.
  composer.json
  composer.lock
  config/default/core.extension.yml
Labels: Bug Fix

#175 WCOR-0: Cleanup of google tag config exports. (Merge to develop)
  config/default/config_split.config_split.prod.yml
  config/envs/prod/google_tag.container.www.washingtoncountyor.gov.yml
  config/envs/prod/google_tag.settings.yml
Labels: Bug Fix, Merge Ready

#185 WCOR-1155: Add Location field to page content type.
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_view_display.node.page.default.yml
  config/default/core.entity_view_display.node.page.teaser.yml
  config/default/field.field.node.page.field_location.yml
Labels: Enhancement, Completed QA, Completed Code Review

#187 WCOR-0: Core update 9.2.6 (main)
  README.md
  composer.json
  composer.lock
Labels: Merge Ready, Hotfix

#188 WCOR-0: Core update 9.2.6 (develop)
  README.md
  composer.json
  composer.lock
Labels: Completed Code Review, Hotfix

#186 WCOR-1179: Add migration status field.
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_view_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.teaser.yml
  config/default/core.entity_view_display.node.page.default.yml
  config/default/core.entity_view_display.node.page.teaser.yml
  config/default/field.field.node.group.field_migration_status.yml
  config/default/field.field.node.page.field_migration_status.yml
  config/default/field.storage.node.field_migration_status.yml
  config/default/language.content_settings.taxonomy_term.migration_status.yml
  config/default/taxonomy.vocabulary.migration_status.yml
  config/default/user.role.content_admin.yml
  config/default/user.role.editor.yml
  config/default/user.role.publisher.yml
Labels: Enhancement, Completed QA, Completed Code Review

#189 WCOR-1120: Add Holiday Schedule field to Service Location content type
  config/default/core.entity_form_display.node.service_location.default.yml
  config/default/core.entity_view_display.node.service_location.default.yml
  config/default/core.entity_view_display.node.service_location.embedded.yml
  config/default/core.entity_view_display.node.service_location.teaser.yml
  config/default/field.field.node.service_location.field_holiday_schedule.yml
  config/default/field.storage.node.field_holiday_schedule.yml
Labels: Enhancement, Completed QA, Completed Code Review

#192 WCOR-1174: Initial Solr indexing configuration settings.
  config/default/search_api.index.acquia_search_index.yml
Labels: Needs Code Review

#197 WCOR-0: Update linkit module to beta3 (main)
  composer.json
  composer.lock
Labels: Merge Ready, Hotfix
