Repository Washington-County/COUNTY-DRUPAL, pull requests merged in 2022-01, with the labels that each got.

#350 WCOR-1239: Clean up and updates.
  composer.json
  composer.lock
  config/default/core.entity_form_display.node.resource.default.yml
  docroot/themes/custom/westy/templates/media/media--document--embedded-with-description.html.twig
  docroot/themes/custom/westy/templates/media/media--document--embedded.html.twig
  docroot/themes/custom/westy/templates/media/media--document--search-result.html.twig
  docroot/themes/custom/westy/templates/media/media--document.html.twig
  docroot/themes/washco/LICENSE.txt
  docroot/themes/washco/config/install/.gitadd
  docroot/themes/washco/css/bootstrap/bootstrap-grid.css
  docroot/themes/washco/css/bootstrap/bootstrap-grid.min.css
  docroot/themes/washco/css/bootstrap/bootstrap-reboot.css
  docroot/themes/washco/css/bootstrap/bootstrap-reboot.min.css
  docroot/themes/washco/css/bootstrap/bootstrap.css
  docroot/themes/washco/css/bootstrap/bootstrap.min.css
  docroot/themes/washco/css/ckeditor.css
  docroot/themes/washco/css/style.css
  docroot/themes/washco/img/right-arrow.svg
  docroot/themes/washco/js/bootstrap/bootstrap.bundle.js
  docroot/themes/washco/js/bootstrap/bootstrap.bundle.js.map
  docroot/themes/washco/js/bootstrap/bootstrap.bundle.min.js
  docroot/themes/washco/js/bootstrap/bootstrap.bundle.min.js.map
  docroot/themes/washco/js/bootstrap/bootstrap.js
  docroot/themes/washco/js/bootstrap/bootstrap.js.map
  docroot/themes/washco/js/bootstrap/bootstrap.min.js
  docroot/themes/washco/js/bootstrap/bootstrap.min.js.map
  docroot/themes/washco/js/main.js
  docroot/themes/washco/js/tether.min.js
  docroot/themes/washco/screenshot.png
  docroot/themes/washco/templates/content/node--faq--embedded.html.twig
  docroot/themes/washco/templates/content/node--faq--search-index.html.twig
  docroot/themes/washco/templates/content/node.html.twig
  docroot/themes/washco/templates/field/field--field-faqs.html.twig
  docroot/themes/washco/templates/field/field.html.twig
  docroot/themes/washco/templates/footer.html.twig
  docroot/themes/washco/templates/header.html.twig
  docroot/themes/washco/templates/html.html.twig
  docroot/themes/washco/templates/media/media--document.html.twig
  docroot/themes/washco/templates/media/media-entity-download-link.html.twig
  docroot/themes/washco/templates/menu/menu--main.html.twig
  docroot/themes/washco/templates/page.html.twig
  docroot/themes/washco/washco.features.yml
  docroot/themes/washco/washco.info.yml
  docroot/themes/washco/washco.libraries.yml
  docroot/themes/washco/washco.theme
Labels: bugfix, enhancement, Completed QA, Completed Code Review

#353 WCOR-0: Fix differences in config export ordering.
  config/default/seckit.settings.yml
  config/envs/prod/simplesamlphp_auth.settings.yml
  config/envs/prod/system.performance.yml
Labels: bugfix, Needs QA, Needs Code Review

#334 WCOR-1226: Refine and style search results display.
  config/default/block.block.contenttype.yml
  config/default/block.block.docs_fy.yml
  config/default/block.block.facetsregionstart.yml
  config/default/block.block.group_2.yml
  config/default/block.block.month.yml
  config/default/block.block.sitemap.yml
  config/default/block.block.westy_account_menu.yml
  config/default/block.block.westy_breadcrumbs.yml
  config/default/block.block.westy_content.yml
  config/default/block.block.westy_page_title.yml
  config/default/block.block.westy_primary_admin_actions.yml
  config/default/block.block.westy_primary_local_tasks.yml
  config/default/block.block.westy_secondary_local_tasks.yml
  config/default/block.block.westy_views_block__alerts_alert_page_block.yml
  config/default/block.block.westy_views_block__building_service_locations_block_1.yml
  config/default/block.block.westy_views_block__manage_group_block_manage_group.yml
  config/default/block.block.westy_views_block__news_block_recent_group_news.yml
  config/default/block.block.westy_views_block__translation_block_1.yml
  config/default/core.extension.yml
  config/default/facets.facet.content_type.yml
  config/default/facets.facet.group.yml
  config/default/facets.facet.news_group.yml
  config/default/facets.facet.news_year.yml
  config/default/facets.facet_source.search_api__views_page__acquia_search__page_search_news.yml
  config/default/views.view.acquia_search.yml
  docroot/modules/custom/wcor/facets_region_start.info.yml
  docroot/modules/custom/wcor/src/Plugin/Block/FacetsRegionStart.php
  docroot/themes/custom/westy/src/scss/base/_elements.scss
  docroot/themes/custom/westy/src/scss/block/_block.scss
  docroot/themes/custom/westy/src/scss/view/_view.scss
Labels: enhancement, Completed QA, Completed Code Review

#354 WCOR-1247: Add Acumin font.
  docroot/themes/custom/westy/src/scss/base/_typography.scss
  docroot/themes/custom/westy/templates/page/page.html.twig
  docroot/themes/custom/westy/templates/system/html.html.twig
Labels: enhancement, Completed QA, Completed Code Review

#338 Activity/WCOR-19 Theme site navigation and header.
  .lando.yml
  config/default/block.block.westy_account_menu.yml
  config/default/views.view.groups.yml
  docroot/themes/custom/westy/assets/images/wcor-logo-temp.png
  docroot/themes/custom/westy/package-lock.json
  docroot/themes/custom/westy/src/js/_header.js
  docroot/themes/custom/westy/src/js/westy.script.js
  docroot/themes/custom/westy/src/scss/base/_variables.scss
  docroot/themes/custom/westy/src/scss/block/_block.scss
  docroot/themes/custom/westy/src/scss/layout/_page.header.scss
  docroot/themes/custom/westy/templates/block/block--system-branding-block.html.twig
  docroot/themes/custom/westy/templates/page/page.header.html.twig
  docroot/themes/custom/westy/templates/page/page.html.twig
  docroot/themes/custom/westy/webpack.mix.js
  docroot/themes/custom/westy/westy.theme
Labels: Needs Changes, Starting Code Review, Starting QA

#356 WCOR-1240: Setup bootstrap list style for side menu.
  docroot/themes/custom/westy/package-lock.json
  docroot/themes/custom/westy/src/scss/base/_mixins.scss
  docroot/themes/custom/westy/templates/menu/menu--site-map.html.twig
  docroot/themes/custom/westy/templates/page/page.html.twig
Labels: enhancement, Completed QA, Completed Code Review

#355 WCOR-1246: Add legacy path to Resource content type.
  config/default/core.entity_form_display.node.resource.default.yml
Labels: enhancement, Completed QA, Completed Code Review

#357 WCOR-20: Theme site footer
  config/default/block_content.type.basic_block.yml
  config/default/core.entity_form_display.block_content.basic_block.default.yml
  config/default/core.entity_view_display.block_content.basic_block.default.yml
  config/default/core.entity_view_mode.block_content.full.yml
  config/default/core.extension.yml
  config/default/field.field.block_content.basic_block.body.yml
  config/default/field.storage.block_content.body.yml
  config/default/language.content_settings.block_content.basic_block.yml
  config/default/system.menu.footer-service-links.yml
  config/default/views.view.block_content.yml
  docroot/themes/custom/westy/assets/images/envelope.svg
  docroot/themes/custom/westy/assets/images/facebook.svg
  docroot/themes/custom/westy/assets/images/googleplus.svg
  docroot/themes/custom/westy/assets/images/if-logo.svg
  docroot/themes/custom/westy/assets/images/index.html
  docroot/themes/custom/westy/assets/images/linkedin.svg
  docroot/themes/custom/westy/assets/images/rss.svg
  docroot/themes/custom/westy/assets/images/twitter.svg
  docroot/themes/custom/westy/assets/images/wcor-color.png
  docroot/themes/custom/westy/assets/images/wcor-color.svg
  docroot/themes/custom/westy/assets/images/wcor-white.png
  docroot/themes/custom/westy/assets/images/wcor-white.svg
  docroot/themes/custom/westy/src/scss/base/_helpers.scss
  docroot/themes/custom/westy/src/scss/layout/_page.footer.scss
  docroot/themes/custom/westy/src/scss/layout/_page.header.scss
  docroot/themes/custom/westy/templates/block/block--system-branding-block.html.twig
  docroot/themes/custom/westy/templates/page/page.footer.html.twig
  docroot/themes/custom/westy/templates/page/page.footer.social.html.twig
  docroot/themes/custom/westy/templates/page/page.html.twig
Labels: enhancement, Completed QA, Completed Code Review

#370 WCOR-1249: Alert component.
  config/default/block.block.westy_views_block__alerts_alert_page_block.yml
  config/default/core.entity_form_display.node.alert.default.yml
  config/default/views.view.alerts.yml
  config/default/views.view.frontpage.yml
  docroot/themes/custom/westy/assets/images/close-o.svg
  docroot/themes/custom/westy/assets/images/danger-alert.svg
  docroot/themes/custom/westy/src/components/alerts/_alerts.js
  docroot/themes/custom/westy/src/js/westy.script.js
  docroot/themes/custom/westy/src/scss/content/node--teaser.html.twig
  docroot/themes/custom/westy/src/scss/layout/_page.header.scss
  docroot/themes/custom/westy/templates/page/page.header.html.twig
  docroot/themes/custom/westy/templates/page/page.html.twig
  docroot/themes/custom/westy/templates/views/views-view-unformatted--alerts--alert-page-block.html.twig
Labels: enhancement, Needs Code Review, Completed QA

#373 WCOR-1251: Enable Group Accordions CKEditor widget.
  config/default/core.extension.yml
  config/default/editor.editor.basic_html.yml
  docroot/modules/custom/custom_ckeditor/ckeditor_accordion/js/plugins/accordion/dialogs/accordion.js
  docroot/modules/custom/custom_ckeditor/ckeditor_groupaccordion/ckeditor_groupaccordion.info.yml
  docroot/modules/custom/custom_ckeditor/ckeditor_groupaccordion/ckeditor_groupaccordion.module
  docroot/modules/custom/custom_ckeditor/ckeditor_groupaccordion/js/plugins/groupaccordion/images/icon-hdpi.png
  docroot/modules/custom/custom_ckeditor/ckeditor_groupaccordion/js/plugins/groupaccordion/images/icon.png
  docroot/modules/custom/custom_ckeditor/ckeditor_groupaccordion/js/plugins/groupaccordion/plugin.js
  docroot/modules/custom/custom_ckeditor/ckeditor_groupaccordion/js/plugins/groupaccordion/styles/widget.css
  docroot/modules/custom/custom_ckeditor/ckeditor_groupaccordion/src/Plugin/CKEditorPlugin/Groupaccordion.php
  docroot/themes/custom/westy/src/scss/components/_accordions.scss
  docroot/themes/custom/westy/src/scss/westy.style.scss
Labels: enhancement, Completed QA, Completed Code Review

#377 WCOR-1252: Homepage featured news component.
  config/default/block.block.views_block__frontpage_homepage_news.yml
  config/default/block.block.westy_content.yml
  config/default/block.block.westy_views_block__news_block_recent_group_news.yml
  config/default/views.view.frontpage.yml
  docroot/themes/custom/westy/src/scss/_cssicons.scss
  docroot/themes/custom/westy/src/scss/components/_callouts.scss
  docroot/themes/custom/westy/src/scss/westy.style.scss
  docroot/themes/custom/westy/templates/page/page--front.html.twig
  docroot/themes/custom/westy/templates/page/page--node--group.html.twig
  docroot/themes/custom/westy/templates/page/page.header.html.twig
  docroot/themes/custom/westy/templates/page/page.html.twig
  docroot/themes/custom/westy/templates/views/views-view-fields--frontpage--homepage-news.html.twig
  docroot/themes/custom/westy/templates/views/views-view-unformatted--frontpage--homepage-main.html.twig
  docroot/themes/custom/westy/templates/views/views-view-unformatted--frontpage--homepage-news.html.twig
Labels: enhancement, Completed QA, Completed Code Review

#387 WCOR-0: Required security updates for core and jquery ui datepicker (develop)
  composer.json
  composer.lock
Labels: Updates, hotfix

#388 WCOR-0: Unify location field and refrence only service locations (develop).
  config/default/core.entity_form_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.default.yml
  config/default/core.entity_view_display.node.group.teaser.yml
  config/default/field.field.node.group.field_location.yml
  config/default/field.field.node.page.field_location.yml
  config/default/field.storage.node.field_primary_service_location.yml
  config/default/views.view.contact_info.yml
  config/default/views.view.groups.yml
Labels: hotfix

#386 WCOR-1246: Update system date formats.
  config/default/core.date_format.default_short_date_time.yml
  config/default/core.date_format.long.yml
  config/default/core.date_format.medium.yml
  config/default/core.date_format.short.yml
  config/default/views.view.content.yml
Labels: Merge Ready, enhancement, Completed QA, Completed Code Review

#396 WCOR-01202022: Empty menu list patch. Displayed in search result fix.
  composer.json
  composer.lock
  config/default/core.entity_view_display.node.service_location.default.yml
  config/default/core.entity_view_display.node.service_location.embedded.yml
  config/default/core.entity_view_display.node.service_location.search_index.yml
  config/default/core.entity_view_display.node.service_location.teaser.yml
  config/default/s3fs.settings.yml
  config/default/views.view.group_reference.yml
Labels: bugfix

#394 WCOR-1243: Content review / approval workflow (with scheduling).
  composer.json
  composer.lock
  config/default/core.entity_form_display.node.contact.default.yml
  config/default/core.entity_form_display.node.news.default.yml
  config/default/core.entity_form_display.node.notification.default.yml
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_view_mode.node.diff.yml
  config/default/core.extension.yml
  config/default/diff.settings.yml
  config/default/scheduler.settings.yml
  config/default/user.role.content_admin.yml
  config/default/user.role.editor.yml
  config/default/user.role.publisher.yml
  config/default/views.view.content_dashboards.yml
  config/default/views.view.media_dashboards.yml
  config/default/workflows.workflow.editorial.yml
Labels: enhancement, Completed QA, Completed Code Review

#405 WCOR-1253-A: Enable featured photo for service location cards.
  config/default/core.entity_view_display.node.group.default.yml
  config/default/core.entity_view_display.node.service_location.default.yml
  config/default/views.view.service_location_display.yml
Labels: Completed QA, Completed Code Review

#413 WCOR-1278: Implement correct headings based on design specs.
  docroot/themes/custom/westy/src/scss/base/_typography.scss
Labels: Starting QA
